# Updates YouTrack tickets to "Ready To Release" when commits with fix(VIM-XXXX): pattern are pushed

name: Close YouTrack on commit

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.repository == 'JetBrains/ideavim'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 300

      - name: Get tags
        run: git fetch --tags origin

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: scripts-ts

        # The last successful job was marked with a tag
      - name: Get commit with last workflow
        run: |
          echo "LAST_COMMIT=$(git rev-list -n 1 tags/workflow-close-youtrack)" >> $GITHUB_ENV

      - name: Update YouTrack
        run: npx tsx src/updateYoutrackOnCommit.ts ..
        working-directory: scripts-ts
        env:
          SUCCESS_COMMIT: ${{ env.LAST_COMMIT }}
          YOUTRACK_TOKEN: ${{ secrets.YOUTRACK_TOKEN }}

      - name: Update tags
        run: |
          git tag --delete workflow-close-youtrack || true
          git push origin :refs/tags/workflow-close-youtrack || true
          git tag workflow-close-youtrack
          git push origin workflow-close-youtrack
