# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Update Authors

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
# Workflow run on push is disabled to avoid conflicts when merging PR
#  push:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.repository == 'JetBrains/ideavim'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 300
          # See end of file updateChangeslog.yml for explanation of this secret
          ssh-key: ${{ secrets.PUSH_TO_PROTECTED_BRANCH_SECRET }}
      - name: Get tags
        run: git fetch --tags origin
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

        # The last successful job was marked with a tag
      - name: Get commit with last workflow
        run: |
          echo "LAST_COMMIT=$(git rev-list -n 1 tags/workflow-authors)" >> $GITHUB_ENV

      - name: Update authors
        id: update_authors
        run: ./gradlew updateAuthors --stacktrace
        env:
          SUCCESS_COMMIT: ${{ env.LAST_COMMIT }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add ${{ steps.update_authors.outputs.authors }} to contributors list
          commit_user_name: IdeaVim Bot
          commit_user_email: maintainers@ideavim.dev
          commit_author: IdeaVim Bot <maintainers@ideavim.dev>
          file_pattern: AUTHORS.md

      - name: Update tags
        run: |
          git tag --delete workflow-authors || true
          git push origin :refs/tags/workflow-authors || true
          git tag workflow-authors
          git push origin workflow-authors
