# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Update Formatting

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.repository == 'JetBrains/ideavim'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          # See end of file updateChangeslog.yml for explanation of this secret
          ssh-key: ${{ secrets.PUSH_TO_PROTECTED_BRANCH_SECRET }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: findologic/intellij-format-action@1.0.1
        with:
          include-glob: '*.kt,*.java'
          path: .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update formatting
          commit_user_name: IdeaVim Bot
          commit_user_email: maintainers@ideavim.dev
          commit_author: IdeaVim Bot <maintainers@ideavim.dev>
